/**
 * SportBuddy
 * API specification for my thesis work SportBuddy
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HalfPositionTypeDTO } from './halfPositionTypeDTO';
import { FullPositionTypeDTO } from './fullPositionTypeDTO';
import { DistanceTypeDTO } from './distanceTypeDTO';
import { CharacteristicsTypeDTO } from './characteristicsTypeDTO';


export interface CharacteristicsDTO { 
    firstHalfPositionType?: HalfPositionTypeDTO;
    firstFullPositionType?: FullPositionTypeDTO;
    secondFullPositionType?: FullPositionTypeDTO;
    secondHalfPositionType?: HalfPositionTypeDTO;
    distanceType?: DistanceTypeDTO;
    type: CharacteristicsTypeDTO;
}

