/**
 * SportBuddy
 * API specification for my thesis work
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: abc@def.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ChatEntryDTO} from './chatEntryDTO';


export interface ChatDTO {
    chatEntries: Array<ChatEntryDTO>;
    image: string;
    primaryId: string;
    users: Array<string>;
    otherParty: string;
}

