/**
 * SportBuddy
 * API specification for my thesis work
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: abc@def.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseMomentDTO } from './exerciseMomentDTO';


export interface ExerciseModelDTO { 
    id: string;
    sequence: Array<ExerciseMomentDTO>;
    sequenceCount: number;
    delay: number;
    /**
     * the 11 character long id of the YouTube video
     */
    videoId: string;
    /**
     * the identifier of the client side text
     */
    name: string;
    /**
     * the identifier of the client side text
     */
    details?: string;
}

